First task
SSKaZZDom/OOP pull request #1
Opened 2022-09-20 01:54 UTC by SSKaZZDom

2022-09-20 13:24 UTC, shadrina requested changes
1. Не проходит сборка
2. Не зарезолвлены варнинги от reviewdog. См. вкладку Files changed.

Назначаем ревьюера только после выполнения этих пунктов.

2022-09-21 06:09 UTC, shadrina requested changes
Много варнингов во вкладке Files changed. Сначала надо их решить, а потом назначать меня ревьюером

2022-09-21 06:10 UTC, shadrina commented
Ой, не на то уведомление отреагировала, сори. Чини

2022-09-25 15:04 UTC, shadrina reviewed
Засчитываю задачу как сданную в срок, так как она первая и замечания не значительны по сравнению с тем, что сделано. В следующий раз к жесткому дедлайну нужно успеть сделать уже хотя бы две итерации ревью, чтобы замечаний не осталось. 
До мерджа нужно внести правки.

2022-09-25 15:04 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/vlomakin/Tests.java
> +public class Tests {
Обычно называют в соответствии с классом, который этот тестовый класс тестируется, т.е. `HeapsortTests`

2022-09-25 15:04 UTC, shadrina commented on Task_1_1_1/build.gradle
> +    implementation 'org.testng:testng:7.1.0'
А зачем понадобилась эта зависимость? Она еще и дублируется

2022-09-25 15:04 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/vlomakin/Tests.java
> +    public void test1() {
Нейминг любых функций должен придумываться на основе того, что функция делает. Например, `testRegularArray`, `testEmptyArray` и тд. Указание номера не имеет смысла.

2022-09-25 15:05 UTC, shadrina commented
И напиши, пожалуйста, имя и фамилию, чтобы я отметила в таблице

2022-09-25 15:15 UTC, SSKaZZDom commented
> И напиши, пожалуйста, имя и фамилию, чтобы я отметила в таблице

Ломакин Владислав
В ближайшее время исправлю замечания, спасибо

2022-09-29 05:29 UTC, shadrina requested changes
В остальном ок

2022-09-29 05:29 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/vlomakin/HeapsortTests.java
> +    public void testReverseArray() {
Не хватает теста на пустой массив и на массив из одного элемента

2022-09-29 05:29 UTC, shadrina commented on Task_1_1_1/script.bat
> +jar cf .\make\jar\Heapsort.jar -C .\make\bin .
Нет исполнения jar'а командой `java`

2022-09-29 05:47 UTC, SSKaZZDom commented on Task_1_1_1/script.bat
> +jar cf .\make\jar\Heapsort.jar -C .\make\bin .
Блин, удалилась в процессе некоторых танцев с бубном и разбирательств с гитом

2022-10-03 09:54 UTC, shadrina approved these changes
Сдано

2022-10-03 16:13 UTC, merged