Task_1_2_1
SSKaZZDom/OOP pull request #2
Opened 2022-10-01 10:19 UTC by SSKaZZDom

2022-10-01 11:02 UTC, SSKaZZDom commented
У меня закончились идеи как поднимать покрытие...

2022-10-03 11:44 UTC, shadrina requested changes

2022-10-03 11:44 UTC, shadrina commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +            }
Может, `limit` сразу выставить в 1 или 2?

2022-10-03 11:44 UTC, shadrina commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +    public Stack<T> popStack(int a) {
Ну придираюсь конечно, но, может, все-таки `n`, а не `a`?..

2022-10-03 11:44 UTC, shadrina commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +    public Stack<T> popStack(int a) {
Или какой-нибудь `size`. А то я читаю код метода и отвлекаюсь на то, чтобы идентифицировать, что за `a`

2022-10-03 11:44 UTC, shadrina commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +        }
Нечитаемо. Тут происходят несложные вещи, можно избавиться от `for`'а в `if`'е.

2022-10-03 11:44 UTC, shadrina commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +        }
Чем не понравился сгенерированный вариант? Или это попытка отформатировать списанный код?)

2022-10-03 16:08 UTC, SSKaZZDom commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +    public Stack<T> popStack(int a) {
Да, я думал про это, но постоянно отвлекался в итоге и не переделал, хорошо

2022-10-03 16:10 UTC, SSKaZZDom commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +        }
Во-первых почти, я эту часть кода изначально подсмотрел, но в итоге всё равно разобрался как сделать так чтобы IDEA подсказывала что надо написать
Во-вторых так надо, потому что код, который был до этого брал во внимание limit, чего мне вообще не хотелось, потому что на мой взгляд стеки в которых лежат одинаковые элементы в одинаковом порядке, но у которых разный limit - одинаковы

2022-10-03 16:10 UTC, SSKaZZDom commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +        }
> 

Во-первых почти, я эту часть кода изначально подсмотрел, но в итоге всё равно разобрался как сделать так чтобы IDEA подсказывала что надо написать
Во-вторых так надо, потому что код, который был до этого брал во внимание limit, чего мне вообще не хотелось, потому что на мой взгляд стеки в которых лежат одинаковые элементы в одинаковом порядке, но у которых разный limit - одинаковы

2022-10-03 16:11 UTC, SSKaZZDom commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +    public Stack<T> popStack(int a) {
> Или какой-нибудь `size`. А то я читаю код метода и отвлекаюсь на то, чтобы идентифицировать, что за `a`

Да, я думал про это, но постоянно отвлекался в итоге и не переделал, хорошо

2022-10-03 16:11 UTC, SSKaZZDom commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +            }
> Может, `limit` сразу выставить в 1 или 2?

То есть не давать пользователю выбирать на сколько элементов он хочет сделать стек? Ну в целом ладно, разумно

2022-10-03 16:11 UTC, SSKaZZDom commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +        }
> Чем не понравился сгенерированный вариант? Или это попытка отформатировать списанный код?)

Во-первых почти, я эту часть кода изначально подсмотрел, но в итоге всё равно разобрался как сделать так чтобы IDEA подсказывала что надо написать
Во-вторых так надо, потому что код, который был до этого брал во внимание limit, чего мне вообще не хотелось, потому что на мой взгляд стеки в которых лежат одинаковые элементы в одинаковом порядке, но у которых разный limit - одинаковы

2022-10-03 16:40 UTC, SSKaZZDom commented
Ладно, это было наивно с моей стороны не запустить тесты перед пушем...

2022-10-05 06:30 UTC, shadrina commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +        }
```java
start = size < n ? size дальше объяснила
```

2022-10-05 06:30 UTC, shadrina commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +    private void realloc(int doubleLimit) {
Вниз

2022-10-05 06:30 UTC, shadrina commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +        if (bool) {
Обсудили

2022-10-05 06:30 UTC, shadrina commented on Task_1_2_1/src/test/java/StackTests.java
> +    public void testPushPop() {
Нет юнит тестов

2022-10-05 09:02 UTC, shadrina approved these changes
Сдано

2022-10-05 09:02 UTC, shadrina commented on Task_1_2_1/src/main/java/org/example/Stack.java
> + * 1 constructor, 5 functions
Лишняя информация. Здесь можно было бы написать что-то про LIFO

2022-10-05 09:02 UTC, shadrina commented on Task_1_2_1/src/main/java/org/example/Stack.java
> +        isSizeEquals = size == eqStack.size;
Тогда уж `isSizeEqual`

2022-11-03 13:41 UTC, merged