Task_1_4_1
SSKaZZDom/OOP pull request #4
Opened 2022-11-29 02:26 UTC by SSKaZZDom

2022-12-08 12:20 UTC, shadrina requested changes

2022-12-08 12:20 UTC, shadrina commented on Task_1_4_1/src/main/java/credit/book/CreditBook.java
> +        diplomaGrades = new HashMap<>();
Вот эту инициализацию можно выносить прямо туда, где декларация.

```java 
Map<Integer, Term> terms = new HashMap<>();
```

2022-12-08 12:20 UTC, shadrina commented on Task_1_4_1/src/main/java/credit/book/CreditBook.java
> +            res = diplomaGrades.get("Qualification work").equals(Grade.EXCELLENT);
Вопрос на сдачу: что из себя представляют enum'ы внутри и почему их можно сравнивать через ==?

2022-12-08 12:20 UTC, shadrina commented on Task_1_4_1/src/main/java/credit/book/CreditBook.java
> +            } // Не смог всунуть это в один if, потому что ограничение длины строки от rewiewdog
Ну, никто не запрещает ставить переносы строк.. И все это удачнее оборачивается в вызовы Stream API

2022-12-08 12:20 UTC, shadrina commented on Task_1_4_1/src/main/java/credit/book/CreditBook.java
> +            }
Stream API

2022-12-08 12:20 UTC, shadrina commented on Task_1_4_1/src/main/java/credit/book/CreditBook.java
> +    private int convert(Grade grade) {
Я бы этот метод унесла в сам enum, он скорее к нему относится, чем к текущему классу

2022-12-08 12:20 UTC, shadrina commented on Task_1_4_1/src/main/java/credit/book/CreditBook.java
> +    private int convert(Grade grade) {
И это конечно должно быть static

2022-12-09 06:21 UTC, SSKaZZDom commented on Task_1_4_1/src/main/java/credit/book/CreditBook.java
> +        diplomaGrades = new HashMap<>();
> Вот эту инициализацию можно выносить прямо туда, где декларация.
> 
> ```java
> Map<Integer, Term> terms = new HashMap<>();
> ```

То есть можно не писать второй раз в конструкторе про это?

2022-12-09 10:06 UTC, shadrina commented on Task_1_4_1/src/main/java/credit/book/CreditBook.java
> +        diplomaGrades = new HashMap<>();
Да

2022-12-10 06:56 UTC, SSKaZZDom commented on Task_1_4_1/src/main/java/credit/book/CreditBook.java
> +            res = diplomaGrades.get("Qualification work").equals(Grade.EXCELLENT);
> Вопрос на сдачу: что из себя представляют enum'ы внутри и почему их можно сравнивать через ==?

enum'ы - набор констант, которые не изменяются и не создаются новые, все ссылки на них - это именно ссылки на те константы, которые были созданы, в моём случае в Grades.java, ну и так как они ссылаются на одно и то же - их можно сравнивать через ==

2022-12-20 11:21 UTC, shadrina approved these changes
👍

2022-12-20 14:12 UTC, merged