Task_2_1_1
SSKaZZDom/OOP pull request #7
Opened 2023-02-13 07:17 UTC by SSKaZZDom

2023-02-28 08:21 UTC, shadrina requested changes

2023-02-28 08:21 UTC, shadrina commented on Task_2_1_1/src/main/java/primenumbers/FindPrime.java
> +        return false;
Можно использовать стримы

2023-02-28 08:21 UTC, shadrina commented on Task_2_1_1/src/main/java/primenumbers/FindWithTreads.java
> +public class FindWithTreads {
Буква в названии пропущена

2023-02-28 08:21 UTC, shadrina commented on Task_2_1_1/src/main/java/primenumbers/FindWithTreads.java
> +    public boolean threadsFinder(List<Integer> list, int count) {
Искатель потоков?

2023-02-28 08:21 UTC, shadrina commented on Task_2_1_1/src/main/java/primenumbers/FindWithTreads.java
> +            }
Давай сделаем отдельный метод, который разобьет список на нужное кол-во подсписков и вернет их? Тут логика немного смешивается.
А так мы разобьем список на нужное число чанков, получим их и одним for'ом создадим нужное число потоков.

2023-02-28 08:21 UTC, shadrina commented on Task_2_1_1/src/main/java/primenumbers/FindWithTreads.java
> +            }
Я бы InterruptedException прописала в throws и переложила бы ответственность за его ловлю на вызывающего. Все равно тут бесполезный RuntimeException кидается

2023-02-28 08:23 UTC, SSKaZZDom commented on Task_2_1_1/src/main/java/primenumbers/FindWithTreads.java
> +    public boolean threadsFinder(List<Integer> list, int count) {
Поточный поисковик :D

2023-02-28 09:01 UTC, SSKaZZDom commented
Названия все я вроде поправил, но не знаю насколько стало лучше с "поточным поисковиком". Разбивать список на подсписки я решил так, как и раньше, хотя есть реализации чужие, но я нашёл только те, которые есть в сторонних библиотеках, типа Guavo, и я не захотел её устанавливать.

2023-03-12 18:44 UTC, shadrina commented on Task_2_1_1/src/main/java/primenumbers/FindPrime.java
> +    boolean res;
private

2023-03-12 18:44 UTC, shadrina commented on Task_2_1_1/src/test/java/primenumbers/PrimeTests.java
> +        System.out.println(System.nanoTime() - start + " 4");
Влад, проблема в том, что в твой замер времени входит генерация входного массива, при увеличении размера это съедает основной кусок времени, поэтому ничего не видно на графике

2023-03-12 18:44 UTC, shadrina commented on Task_2_1_1/src/main/java/primenumbers/FindWithThreads.java
> +        List<List<Integer>> lists = subLists(list, count);
Все-таки неудачный был совет. Не бойтесь мне возражать, если моя идея не работает

2023-03-12 18:46 UTC, shadrina commented on Task_2_1_1/src/test/java/primenumbers/PrimeTests.java
> +        System.out.println(System.nanoTime() - start + " 4");
Измерять надо `fwt.threadPrimeFinder(test, 4)`

2023-03-20 08:21 UTC, shadrina requested changes

2023-03-20 08:21 UTC, shadrina commented on Task_2_1_1/src/main/java/primenumbers/FindPrime.java
> +    public boolean doNotHavePrime() {
`hasNonPrime`? Текущее название не соответствует реальному назначению

2023-03-20 08:21 UTC, shadrina commented on Task_2_1_1/src/test/java/primenumbers/PrimeTests.java
> +            }
1. Хочется наконец-то сдать, понимаю, но тут весь файл в копипасте. Его можно уменьшить в n раз, если просто вынести все, что повторяется, в отдельный метод.
2. Верно ли я читаю, что в тесте присутствуют любые числа вперемешку -- и простые, и составные? Наиболее показательной будет тест дата, в которой либо есть одно составное, либо составных вообще нет. Понимаешь почему?

2023-03-21 07:52 UTC, shadrina approved these changes

2023-03-27 04:45 UTC, merged